# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: double-quote-string-fixer
    -   id: mixed-line-ending


# If you want to avoid flake8 errors due to unused vars or imports:
- repo: https://github.com/PyCQA/autoflake
  rev: v2.0.0
  hooks:
  - id: autoflake
    args: [
      --in-place,
      --remove-all-unused-imports,
      --remove-unused-variables,
    ]

- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
  ## You can add flake8 plugins via `additional_dependencies`:
  #  additional_dependencies: [flake8-bugbear]

- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score
        ]


- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.902
  hooks:
    - id: mypy
      additional_dependencies: [types-requests, pandas-stubs, Jinja2]
